import React, { createContext, useContext, useState } from 'react';

const LanguageContext = createContext();

export const translations = {
  pt: {
    /* ===== NAVBAR ===== */
    nav_home: 'Home',
    nav_work: 'Trabalho',
    nav_about: 'Sobre',
    nav_contact: 'Contato',
    nav_whatsapp: 'WhatsApp →',

    /* ===== HERO ===== */
    hero_role: 'Motion designer',
    hero_location: 'Goiânia, BR',
    hero_available: 'Disponível',
    hero_aka: 'aka Guga',
    hero_title_1: 'Motion design',
    hero_title_2: 'que vende.',
    hero_subtitle: 'Animações e criativos que prendem atenção, vendem e te deixam com cara de marca grande.',
    hero_stat_projects: 'projetos',
    hero_stat_years: 'anos',
    hero_stat_response: 'resposta',
    hero_cta_meet: 'Quer me conhecer?',
    hero_cta_whatsapp: 'Falar no WhatsApp →',
    hero_scroll: 'Showreel rolando ali embaixo',

    /* ===== SHOWREEL ===== */
    showreel_stories_eyebrow: 'Showreel · Stories',
    showreel_wide_eyebrow: 'Widescreen',
    showreel_wide_title_1: 'Em formato',
    showreel_wide_title_2: 'cinematográfico.',
    showreel_wide_subtitle: 'Brand films, edições longas e peças horizontais',
    showreel_novos_eyebrow: 'Novidades',
    showreel_novos_title_1: 'Trabalhos',
    showreel_novos_title_2: 'recentes.',
    showreel_novos_subtitle: 'Os drops mais novos saindo do forno',
    showreel_mix_eyebrow: 'Mix',
    showreel_mix_title_1: 'Mistura de',
    showreel_mix_title_2: 'formatos.',
    showreel_mix_subtitle: 'Verticais, quadrados e horizontais lado a lado',

    /* ===== STATS BANNER ===== */
    stats_eyebrow: 'Por que motion?',
    stats_title_1: 'Vídeo não é luxo,',
    stats_title_2: 'é matemática.',
    stats_1_label: 'mais engajamento',
    stats_1_source: 'em posts com motion (Wyzowl, 2024)',
    stats_2_label: 'compram após vídeo',
    stats_2_source: 'dos consumidores convertem com vídeo de marca (HubSpot)',
    stats_3_label: 'pra prender atenção',
    stats_3_source: 'tempo médio que um vídeo tem no feed',

    /* ===== PROCESS ===== */
    process_eyebrow: 'Como funciona',
    process_title_1: 'Do brief ao reel',
    process_title_2: 'em 3 passos.',
    process_subtitle: 'Sem mistério, sem enrolação. Você sabe exatamente o que esperar.',
    process_step_1_title: 'Briefing',
    process_step_1_time: '24h',
    process_step_1_desc: 'Você manda o brief no WhatsApp. Em até 24h respondo com proposta clara — escopo, prazo e investimento.',
    process_step_2_title: 'Criação',
    process_step_2_time: '3-5 dias',
    process_step_2_desc: 'Primeira versão entregue em até 5 dias. Você revisa, eu ajusto. Até 2 rodadas de revisão inclusas no Pro.',
    process_step_3_title: 'Entrega',
    process_step_3_time: 'Mesmo dia',
    process_step_3_desc: 'Arquivo final em todos os formatos pedidos (16:9, 9:16, 1:1) prontos pra postar — sem retrabalho.',

    /* ===== PACKAGES ===== */
    pkg_eyebrow: 'Packs',
    pkg_title_1: 'Packs pra colocar sua marca',
    pkg_title_2: 'em movimento.',
    pkg_subtitle: 'Vídeos curtos, diretos e com visual profissional pra destacar seu negócio nas redes.',
    pkg_price_from: 'A partir de',
    pkg_price_until: 'até',
    pkg_price_investment: 'Investimento',
    pkg_pack_label: 'Pack',
    pkg_badge_featured: 'Mais escolhido',
    pkg_start_eyebrow: 'Pra começar com motion',
    pkg_start_note: 'Ideal pra negócios que querem testar conteúdo profissional',
    pkg_start_cta: 'Quero o Start',
    pkg_start_f1: '1 reel até 15s',
    pkg_start_f2: '1 rodada de revisão',
    pkg_start_f3: 'Cortes, ritmo e legendas',
    pkg_start_f4: 'Acabamento visual profissional',
    pkg_start_f5: 'Entrega rápida (até 5 dias)',
    pkg_pro_eyebrow: 'Mais escolhido',
    pkg_pro_note: 'Pra marcas que querem consistência e aparência profissional',
    pkg_pro_cta: 'Quero o Pro',
    pkg_pro_f1: '3 a 5 reels curtos',
    pkg_pro_f2: 'Motion design leve/moderado',
    pkg_pro_f3: 'Identidade visual aplicada',
    pkg_pro_f4: 'Até 2 rodadas de revisão',
    pkg_pro_f5: 'Trilha sonora licenciada',
    pkg_pro_f6: 'Entrega em 7-10 dias',
    pkg_premium_eyebrow: 'Projetos grandes',
    pkg_premium_price: 'Sob consulta',
    pkg_premium_footnote: 'a partir de R$ 3.500',
    pkg_premium_note: 'Pra empresas que querem presença forte nas redes',
    pkg_premium_cta: 'Pedir orçamento',
    pkg_premium_f1: 'Pacote completo de vídeos',
    pkg_premium_f2: 'Direção visual',
    pkg_premium_f3: 'Motion design avançado',
    pkg_premium_f4: 'Campanha, lançamento ou recorrente',
    pkg_premium_f5: 'Prazo e escopo customizados',
    pkg_cta_main: 'Pedir orçamento',
    pkg_cta_secondary: 'Ver trabalhos',
    pkg_footnote: 'Pagamento em PIX, transferência ou Stripe · Nota fiscal disponível',

    /* ===== FAQ ===== */
    faq_eyebrow: 'FAQ',
    faq_title_1: 'Perguntas que',
    faq_title_2: 'todo mundo faz.',
    faq_help: 'Ficou alguma dúvida?',
    faq_link: 'Manda no WhatsApp →',
    faq_1_q: 'Quanto tempo demora pra entregar?',
    faq_1_a: 'Pacote Start: 3-5 dias úteis. Pacote Pro: 7-10 dias. Brand films e projetos sob medida: 2-3 semanas, dependendo do escopo. Combinamos prazo certo no briefing.',
    faq_2_q: 'Quantas revisões estão inclusas?',
    faq_2_a: 'Start: 1 rodada de revisão. Pro: até 2 rodadas. Revisões extras são cobradas à parte (combinadas antes de começar). 90% dos projetos fecham dentro das revisões inclusas.',
    faq_3_q: 'Atende fora de Goiânia?',
    faq_3_a: 'Sim — 100% remoto. Tudo via WhatsApp, e-mail e chamada quando precisar. Já entreguei projetos pra clientes em SP, RJ, BH, Floripa e Lisboa.',
    faq_4_q: 'Em quais formatos é entregue?',
    faq_4_a: 'MP4 (H.264) nos formatos que você pedir — 16:9 (YouTube/site), 9:16 (Reels/TikTok/Stories), 1:1 (feed Instagram). O projeto fonte (.aep do After Effects) vem incluso no Pacote Pro.',
    faq_5_q: 'Como funciona o pagamento?',
    faq_5_a: '50% na aprovação do briefing + 50% na entrega final. Aceito PIX, transferência ou Stripe (pra clientes do exterior). Nota fiscal disponível mediante solicitação.',

    /* ===== CTA SECTION (home final) ===== */
    cta_eyebrow: 'Vamos trabalhar juntos',
    cta_title_1: 'Curtiu o trabalho?',
    cta_title_2: 'Bora tirar sua ideia do papel.',
    cta_subtitle: 'Me chama no WhatsApp — te ajudo com motion design, animações e criativos que realmente chamam atenção e geram resultado.',
    cta_stat_1_label: 'anos de experiência',
    cta_stat_2_label: 'projetos entregues',
    cta_stat_3_label: 'dedicação',
    cta_button: 'Pedir orçamento no WhatsApp',
    cta_footnote: 'Resposta em até 24h · Orçamento sem compromisso',

    /* ===== ABOUT ===== */
    about_eyebrow: 'Sobre',
    about_title_1: 'Sou o',
    about_title_2: 'Guga.',
    about_name: 'Gustavo Leão',
    about_role: 'Motion designer & animador',
    about_location: 'Goiânia, Brasil',
    about_years: '3+ anos no mercado',
    about_available: 'Disponível',
    about_cta_whatsapp: 'Falar no WhatsApp',
    about_cta_works: 'Ver os trabalhos',
    about_manifesto_1: 'Motion design não é decoração.',
    about_manifesto_2: 'É linguagem de venda.',
    about_manifesto_sign: '— Guga, em algum brainstorm',
    about_story_eyebrow: 'Minha história',
    about_bio_1: 'Sou o Guga, motion designer há mais de 3 anos. Trabalho com marcas, negócios e criadores que querem se destacar no feed e convencer no scroll.',
    about_bio_2: 'Penso motion como linguagem de venda: ritmo certo, atenção no segundo certo, e mensagem que para o dedo de quem tá rolando. Animar é o meio — vender (sua ideia, marca ou produto) é o objetivo.',
    about_bio_3: 'Atendimento 100% remoto. Já entreguei projetos pra clientes em Goiânia, SP, RJ, BH, Florianópolis e Lisboa. Comunicação direta, prazo respeitado, sem enrolação.',
    about_stat_1_label: 'anos de motion',
    about_stat_2_label: 'projetos entregues',
    about_stat_3_label: 'tempo de resposta',
    about_stat_4_label: 'remoto',
    about_tools_eyebrow: 'Ferramentas',
    about_tools_title: 'Com o que eu trabalho',
    about_final_eyebrow: 'Bora trabalhar juntos?',
    about_final_title_1: 'Manda sua',
    about_final_title_2: 'ideia.',
    about_final_subtitle: 'Resposta em até 24h · Orçamento sem compromisso · Atendimento remoto',

    /* ===== TRABALHOS ===== */
    works_eyebrow: 'Portfólio',
    works_title_1: 'Todos os',
    works_title_2: 'trabalhos.',
    works_subtitle: 'vídeos · clica nos filtros pra ver por categoria',
    works_filter_all: 'Todos',
    works_filter_clear: 'Limpar',
    works_empty_title: 'Nenhum vídeo dessa categoria',
    works_empty_subtitle: 'Tenta outro filtro acima',
    works_cta_title: 'Gostou do trabalho?',
    works_cta_subtitle: 'Vamos transformar sua ideia em motion. Manda no WhatsApp e a gente conversa.',
    works_cta_button: 'Falar no WhatsApp',

    /* ===== CONTACT ===== */
    contact_eyebrow: 'Contato',
    contact_title_1: 'Vamos criar algo',
    contact_title_2: 'incrível juntos.',
    contact_subtitle: 'Me conta sua ideia e eu respondo em até 24h com o melhor caminho pra tirar ela do papel.',
    contact_whatsapp_title: 'Falar direto no WhatsApp',
    contact_whatsapp_subtitle: 'Resposta em até 24h · Orçamento sem compromisso',
    contact_whatsapp_cta: 'Iniciar conversa',
    contact_divider: 'ou deixa uma mensagem aqui',
    contact_project_type: 'Que tipo de projeto?',
    contact_type_reel: 'Reel / Social',
    contact_type_brand: 'Brand film',
    contact_type_campaign: 'Campanha',
    contact_type_vinheta: 'Vinheta / Logo',
    contact_type_other: 'Outro',
    contact_name_label: 'Seu nome',
    contact_name_placeholder: 'Como posso te chamar?',
    contact_message_label: 'Sobre o projeto',
    contact_message_placeholder: 'Me conta: o que precisa? prazo? referência visual? Quanto mais detalhe, melhor.',
    contact_send: 'Enviar pelo WhatsApp',
    contact_success_title: 'Show!',
    contact_success_subtitle: 'Sua mensagem foi aberta no WhatsApp. Bora conversar e tirar essa ideia do papel.',
    contact_footer_response: 'Resposta em até 24h',
    contact_footer_remote: '100% remoto',
    contact_footer_quote: 'Sem compromisso',

    /* ===== FOOTER ===== */
    footer_desc: 'Motion design que vende. Animações e vídeos para marcas que querem se destacar.',
    navigation: 'Navegação',
    rights: 'Todos os direitos reservados',
    design_dev: 'Design & Desenvolvimento',
    footer_contact: 'Contato',
  },

  en: {
    /* ===== NAVBAR ===== */
    nav_home: 'Home',
    nav_work: 'Work',
    nav_about: 'About',
    nav_contact: 'Contact',
    nav_whatsapp: 'WhatsApp →',

    /* ===== HERO ===== */
    hero_role: 'Motion designer',
    hero_location: 'Goiânia, BR',
    hero_available: 'Available',
    hero_aka: 'aka Guga',
    hero_title_1: 'Motion design',
    hero_title_2: 'that sells.',
    hero_subtitle: 'Animations and creative pieces that hold attention, sell, and make your brand look big.',
    hero_stat_projects: 'projects',
    hero_stat_years: 'years',
    hero_stat_response: 'response',
    hero_cta_meet: 'Want to know me?',
    hero_cta_whatsapp: 'Chat on WhatsApp →',
    hero_scroll: 'Showreel rolling below',

    /* ===== SHOWREEL ===== */
    showreel_stories_eyebrow: 'Showreel · Stories',
    showreel_wide_eyebrow: 'Widescreen',
    showreel_wide_title_1: 'In a',
    showreel_wide_title_2: 'cinematic format.',
    showreel_wide_subtitle: 'Brand films, long edits and horizontal pieces',
    showreel_novos_eyebrow: 'New',
    showreel_novos_title_1: 'Recent',
    showreel_novos_title_2: 'work.',
    showreel_novos_subtitle: 'Fresh drops, right out of the oven',
    showreel_mix_eyebrow: 'Mix',
    showreel_mix_title_1: 'Mixed',
    showreel_mix_title_2: 'formats.',
    showreel_mix_subtitle: 'Vertical, square and horizontal side by side',

    /* ===== STATS BANNER ===== */
    stats_eyebrow: 'Why motion?',
    stats_title_1: 'Video isn\'t luxury,',
    stats_title_2: 'it\'s math.',
    stats_1_label: 'more engagement',
    stats_1_source: 'on posts with motion (Wyzowl, 2024)',
    stats_2_label: 'buy after a video',
    stats_2_source: 'of consumers convert with brand video (HubSpot)',
    stats_3_label: 'to grab attention',
    stats_3_source: 'average time a video has in the feed',

    /* ===== PROCESS ===== */
    process_eyebrow: 'How it works',
    process_title_1: 'From brief to reel',
    process_title_2: 'in 3 steps.',
    process_subtitle: 'No mystery, no bullshit. You know exactly what to expect.',
    process_step_1_title: 'Briefing',
    process_step_1_time: '24h',
    process_step_1_desc: 'Send the brief on WhatsApp. Within 24h I reply with a clear proposal — scope, timeline and price.',
    process_step_2_title: 'Creation',
    process_step_2_time: '3-5 days',
    process_step_2_desc: 'First version delivered in up to 5 days. You review, I adjust. Up to 2 revision rounds included in Pro.',
    process_step_3_title: 'Delivery',
    process_step_3_time: 'Same day',
    process_step_3_desc: 'Final files in all requested formats (16:9, 9:16, 1:1) ready to post — no rework needed.',

    /* ===== PACKAGES ===== */
    pkg_eyebrow: 'Packs',
    pkg_title_1: 'Packs to put your brand',
    pkg_title_2: 'in motion.',
    pkg_subtitle: 'Short, direct videos with professional visuals to make your business stand out on social.',
    pkg_price_from: 'From',
    pkg_price_until: 'up to',
    pkg_price_investment: 'Investment',
    pkg_pack_label: 'Pack',
    pkg_badge_featured: 'Most chosen',
    pkg_start_eyebrow: 'To start with motion',
    pkg_start_note: 'Ideal for small businesses testing professional content',
    pkg_start_cta: 'I want Start',
    pkg_start_f1: '1 reel up to 15s',
    pkg_start_f2: '1 revision round',
    pkg_start_f3: 'Cuts, pacing and captions',
    pkg_start_f4: 'Professional visual finish',
    pkg_start_f5: 'Fast delivery (up to 5 days)',
    pkg_pro_eyebrow: 'Most chosen',
    pkg_pro_note: 'For brands that want consistency and a professional look',
    pkg_pro_cta: 'I want Pro',
    pkg_pro_f1: '3 to 5 short reels',
    pkg_pro_f2: 'Light/moderate motion design',
    pkg_pro_f3: 'Applied visual identity',
    pkg_pro_f4: 'Up to 2 revision rounds',
    pkg_pro_f5: 'Licensed soundtrack',
    pkg_pro_f6: 'Delivery in 7-10 days',
    pkg_premium_eyebrow: 'Big projects',
    pkg_premium_price: 'Custom quote',
    pkg_premium_footnote: 'starting at R$ 3,500',
    pkg_premium_note: 'For companies that want a strong presence on social',
    pkg_premium_cta: 'Get a quote',
    pkg_premium_f1: 'Full video package',
    pkg_premium_f2: 'Visual direction',
    pkg_premium_f3: 'Advanced motion design',
    pkg_premium_f4: 'Campaign, launch or recurring',
    pkg_premium_f5: 'Custom timeline and scope',
    pkg_cta_main: 'Get a quote',
    pkg_cta_secondary: 'See works',
    pkg_footnote: 'Payment via PIX, transfer or Stripe · Invoice available',

    /* ===== FAQ ===== */
    faq_eyebrow: 'FAQ',
    faq_title_1: 'Questions',
    faq_title_2: 'everyone asks.',
    faq_help: 'Got any other questions?',
    faq_link: 'Message on WhatsApp →',
    faq_1_q: 'How long does delivery take?',
    faq_1_a: 'Start pack: 3-5 business days. Pro pack: 7-10 days. Brand films and custom projects: 2-3 weeks, depending on scope. We agree on the timeline in the briefing.',
    faq_2_q: 'How many revisions are included?',
    faq_2_a: 'Start: 1 revision round. Pro: up to 2 rounds. Extra revisions are charged separately (agreed before starting). 90% of projects wrap within included revisions.',
    faq_3_q: 'Do you work outside Goiânia?',
    faq_3_a: 'Yes — 100% remote. Everything via WhatsApp, email and calls when needed. I\'ve delivered projects for clients in SP, RJ, BH, Floripa and Lisbon.',
    faq_4_q: 'Which delivery formats?',
    faq_4_a: 'MP4 (H.264) in the formats you need — 16:9 (YouTube/website), 9:16 (Reels/TikTok/Stories), 1:1 (Instagram feed). The After Effects source (.aep) is included in the Pro pack.',
    faq_5_q: 'How does payment work?',
    faq_5_a: '50% on brief approval + 50% on final delivery. I accept PIX, bank transfer or Stripe (for international clients). Invoice available on request.',

    /* ===== CTA SECTION ===== */
    cta_eyebrow: 'Let\'s work together',
    cta_title_1: 'Liked the work?',
    cta_title_2: 'Let\'s bring your idea to life.',
    cta_subtitle: 'Hit me up on WhatsApp — I\'ll help with motion design, animations and creative pieces that actually grab attention and drive results.',
    cta_stat_1_label: 'years of experience',
    cta_stat_2_label: 'projects delivered',
    cta_stat_3_label: 'dedication',
    cta_button: 'Get a quote on WhatsApp',
    cta_footnote: 'Reply within 24h · No-obligation quote',

    /* ===== ABOUT ===== */
    about_eyebrow: 'About',
    about_title_1: 'I\'m',
    about_title_2: 'Guga.',
    about_name: 'Gustavo Leão',
    about_role: 'Motion designer & animator',
    about_location: 'Goiânia, Brazil',
    about_years: '3+ years in the game',
    about_available: 'Available',
    about_cta_whatsapp: 'Chat on WhatsApp',
    about_cta_works: 'See the works',
    about_manifesto_1: 'Motion design isn\'t decoration.',
    about_manifesto_2: 'It\'s the language of sales.',
    about_manifesto_sign: '— Guga, during some brainstorm',
    about_story_eyebrow: 'My story',
    about_bio_1: 'I\'m Guga, a motion designer with 3+ years in the field. I work with brands, businesses and creators who want to stand out in the feed and convince on the scroll.',
    about_bio_2: 'I think of motion as the language of sales: right pacing, attention at the right second, and a message that stops the thumb of whoever\'s scrolling. Animation is the means — selling (your idea, brand or product) is the goal.',
    about_bio_3: '100% remote work. I\'ve delivered projects for clients in Goiânia, SP, RJ, BH, Florianópolis and Lisbon. Direct communication, respected deadlines, no bullshit.',
    about_stat_1_label: 'years of motion',
    about_stat_2_label: 'projects delivered',
    about_stat_3_label: 'response time',
    about_stat_4_label: 'remote',
    about_tools_eyebrow: 'Tools',
    about_tools_title: 'What I work with',
    about_final_eyebrow: 'Let\'s work together?',
    about_final_title_1: 'Send your',
    about_final_title_2: 'idea.',
    about_final_subtitle: 'Reply within 24h · No-obligation quote · Remote work',

    /* ===== TRABALHOS ===== */
    works_eyebrow: 'Portfolio',
    works_title_1: 'All',
    works_title_2: 'the works.',
    works_subtitle: 'videos · click filters to see by category',
    works_filter_all: 'All',
    works_filter_clear: 'Clear',
    works_empty_title: 'No videos in this category',
    works_empty_subtitle: 'Try another filter above',
    works_cta_title: 'Liked the work?',
    works_cta_subtitle: 'Let\'s turn your idea into motion. Hit me up on WhatsApp.',
    works_cta_button: 'Chat on WhatsApp',

    /* ===== CONTACT ===== */
    contact_eyebrow: 'Contact',
    contact_title_1: 'Let\'s build something',
    contact_title_2: 'amazing together.',
    contact_subtitle: 'Tell me your idea and I\'ll reply within 24h with the best way to bring it to life.',
    contact_whatsapp_title: 'Chat directly on WhatsApp',
    contact_whatsapp_subtitle: 'Reply within 24h · No-obligation quote',
    contact_whatsapp_cta: 'Start chat',
    contact_divider: 'or drop a message here',
    contact_project_type: 'What kind of project?',
    contact_type_reel: 'Reel / Social',
    contact_type_brand: 'Brand film',
    contact_type_campaign: 'Campaign',
    contact_type_vinheta: 'Vignette / Logo',
    contact_type_other: 'Other',
    contact_name_label: 'Your name',
    contact_name_placeholder: 'What should I call you?',
    contact_message_label: 'About the project',
    contact_message_placeholder: 'Tell me: what do you need? timeline? visual reference? The more detail, the better.',
    contact_send: 'Send via WhatsApp',
    contact_success_title: 'Nice!',
    contact_success_subtitle: 'Your message was opened in WhatsApp. Let\'s chat and bring this idea to life.',
    contact_footer_response: 'Reply within 24h',
    contact_footer_remote: '100% remote',
    contact_footer_quote: 'No obligation',

    /* ===== FOOTER ===== */
    footer_desc: 'Motion design that sells. Animations and videos for brands that want to stand out.',
    navigation: 'Navigation',
    rights: 'All rights reserved',
    design_dev: 'Design & Development',
    footer_contact: 'Contact',
  },
};

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState('pt');
  const t = (key) => translations[lang]?.[key] || translations.pt[key] || key;
  return (
    <LanguageContext.Provider value={{ lang, setLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error('useLanguage must be used within LanguageProvider');
  return ctx;
}
